# Generated by Django 5.0.2 on 2024-04-04 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_productbooking',
            name='customer',
        ),
        migrations.DeleteModel(
            name='tbl_cart',
        ),
        migrations.DeleteModel(
            name='tbl_productbooking',
        ),
    ]
