# Generated by Django 5.0.2 on 2024-04-19 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0064_delete_aboutussimple'),
        ('Customer', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_cart',
            new_name='tbl_pcart',
        ),
    ]
