# Generated by Django 5.0.2 on 2024-04-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_rename_tbl_cart_tbl_pcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_pcart',
            name='ship_status',
            field=models.IntegerField(default='0'),
        ),
    ]
