# Generated by Django 5.0.2 on 2024-04-24 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0064_delete_aboutussimple'),
        ('Customer', '0007_remove_tbl_productbooking_customer_delete_tbl_pcart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_productbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booking_status', models.IntegerField(default='0')),
                ('price', models.CharField(default='0', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_pcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_qty', models.CharField(max_length=500)),
                ('cart_status', models.IntegerField(default='0')),
                ('ship_status', models.IntegerField(default='0')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_newproduct')),
            ],
        ),
    ]
