# Generated by Django 5.0.2 on 2024-04-24 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_tbl_productbooking_tbl_pcart'),
        ('Guest', '0011_tbl_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_productbooking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_customer'),
        ),
        migrations.AddField(
            model_name='tbl_pcart',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.tbl_productbooking'),
        ),
    ]
