# Generated by Django 5.0.2 on 2024-04-25 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_tbl_productbooking_customer_tbl_pcart_booking'),
        ('Guest', '0011_tbl_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_customer'),
        ),
    ]
