# Generated by Django 5.0.2 on 2024-04-25 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_alter_tbl_complaint_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
