# Generated by Django 5.0.2 on 2024-04-25 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0012_tbl_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
