# Generated by Django 5.0.2 on 2024-04-25 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0014_tbl_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
    ]
