# Generated by Django 5.0.2 on 2024-04-03 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_productbooking',
            name='staff',
        ),
        migrations.DeleteModel(
            name='tbl_cart',
        ),
        migrations.DeleteModel(
            name='tbl_productbooking',
        ),
    ]
