# Generated by Django 5.0.2 on 2024-04-08 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0062_tbl_stock'),
        ('Staff', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('rawmaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_rawmaterial')),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_supplier')),
            ],
        ),
    ]
