# Generated by Django 5.0.2 on 2024-04-28 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0004_tbl_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_purchase',
        ),
    ]
