# Generated by Django 5.0.2 on 2024-02-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0008_tbl_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_subject',
            new_name='tbl_semester',
        ),
        migrations.RenameField(
            model_name='tbl_semester',
            old_name='subject_name',
            new_name='semester_name',
        ),
    ]
