# Generated by Django 5.0.2 on 2024-02-21 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0010_tbl_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_subject')),
            ],
        ),
    ]
