# Generated by Django 5.0.2 on 2024-02-26 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0013_tbl_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_product',
        ),
    ]
