# Generated by Django 5.0.2 on 2024-02-26 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0015_tbl_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_galleryproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryproduct_description', models.CharField(max_length=50)),
                ('product_photo', models.FileField(upload_to='Assets/UserPhoto/')),
                ('product_status', models.IntegerField(default='0')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_product')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_subcategory')),
            ],
        ),
    ]
