# Generated by Django 5.0.2 on 2024-03-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0018_tbl_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.CharField(max_length=50)),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
    ]
