# Generated by Django 5.0.2 on 2024-03-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0020_tbl_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_supplier',
            old_name='GstNo',
            new_name='supplier_gstno',
        ),
    ]
