# Generated by Django 5.0.2 on 2024-03-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0021_rename_gstno_tbl_supplier_supplier_gstno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_staff',
        ),
    ]
