# Generated by Django 5.0.2 on 2024-03-11 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0027_tbl_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_staff',
        ),
    ]
