# Generated by Django 5.0.2 on 2024-03-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0029_tbl_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rawmaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawmaterial_id', models.CharField(max_length=50)),
                ('rawmaterial_name', models.CharField(max_length=50)),
            ],
        ),
    ]
