# Generated by Django 5.0.2 on 2024-03-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0030_tbl_rawmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(max_length=50)),
                ('unit_name', models.CharField(max_length=50)),
            ],
        ),
    ]
