# Generated by Django 5.0.2 on 2024-03-20 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0032_tbl_newproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_staff',
        ),
    ]
