# Generated by Django 5.0.2 on 2024-03-20 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0033_delete_tbl_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50)),
                ('staff_name', models.CharField(max_length=50)),
                ('staff_phone', models.CharField(max_length=50)),
                ('staff_email', models.CharField(max_length=50)),
                ('staff_address', models.CharField(max_length=50)),
                ('staff_dob', models.CharField(max_length=50)),
                ('staff_password', models.CharField(max_length=50)),
                ('staff_photo', models.FileField(upload_to='Assets/staffphoto/')),
                ('staff_proof', models.FileField(upload_to='Assets/staffproof/')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_role')),
            ],
        ),
    ]
