# Generated by Django 5.0.2 on 2024-03-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0036_tbl_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_newproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tbl_newproduct',
            name='unit',
        ),
        migrations.DeleteModel(
            name='tbl_rawmaterial',
        ),
        migrations.RemoveField(
            model_name='tbl_staff',
            name='role',
        ),
        migrations.DeleteModel(
            name='tbl_newproduct',
        ),
        migrations.DeleteModel(
            name='tbl_unit',
        ),
        migrations.DeleteModel(
            name='tbl_staff',
        ),
    ]
