# Generated by Django 5.0.2 on 2024-03-20 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0040_tbl_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_newproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newproduct_name', models.CharField(max_length=50)),
                ('newproduct_price', models.CharField(max_length=50)),
                ('newproduct_details', models.CharField(max_length=50)),
                ('newproduct_stock', models.CharField(max_length=50)),
                ('newproduct_photo', models.FileField(upload_to='Assets/UserPhoto/')),
                ('newproduct_status', models.IntegerField(default='0')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_category')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_unit')),
            ],
        ),
    ]
