# Generated by Django 5.0.2 on 2024-03-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0041_tbl_unit_tbl_newproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rawmaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawmaterial_name', models.CharField(max_length=150)),
            ],
        ),
    ]
