# Generated by Django 5.0.2 on 2024-03-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0042_tbl_rawmaterial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_rawmaterial',
            old_name='rawmaterial_name',
            new_name='rawmaterial',
        ),
        migrations.RenameField(
            model_name='tbl_unit',
            old_name='unit_name',
            new_name='unit',
        ),
    ]
