# Generated by Django 5.0.2 on 2024-03-21 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0043_rename_rawmaterial_name_tbl_rawmaterial_rawmaterial_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_admin',
        ),
    ]
