# Generated by Django 5.0.2 on 2024-03-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0044_delete_tbl_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_email', models.CharField(max_length=50)),
                ('admin_phone', models.CharField(max_length=50)),
                ('admin_password', models.CharField(max_length=50)),
                ('admin_photo', models.FileField(upload_to='Assets/UserPhoto/')),
            ],
        ),
    ]
