# Generated by Django 5.0.2 on 2024-03-22 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0045_tbl_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_supplier',
        ),
    ]
