# Generated by Django 5.0.2 on 2024-03-25 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0047_tbl_supplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_supplier',
        ),
    ]
