# Generated by Django 5.0.2 on 2024-03-25 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0053_tbl_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rawmaterialcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawmaterial_qty', models.CharField(max_length=50)),
                ('rawmaterial_date', models.CharField(max_length=50)),
                ('rawmaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_rawmaterial')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_unit')),
            ],
        ),
    ]
