# Generated by Django 5.0.2 on 2024-03-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0056_tbl_rawmaterialcons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rawmaterialcons',
        ),
    ]
