# Generated by Django 5.0.2 on 2024-03-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0059_tbl_production'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_production',
        ),
    ]
