# Generated by Django 5.0.2 on 2024-03-25 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0060_delete_tbl_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.CharField(max_length=50)),
                ('production_qty', models.CharField(max_length=50)),
                ('newproduct_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_newproduct')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_unit')),
            ],
        ),
    ]
