# Generated by Django 5.0.2 on 2024-04-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0062_tbl_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
