# Generated by Django 5.0.2 on 2024-04-18 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0063_aboutussimple'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUsSimple',
        ),
    ]
