# Generated by Django 5.0.2 on 2024-04-25 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0064_delete_aboutussimple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_newproduct'),
        ),
    ]
