# Generated by Django 5.0.2 on 2024-02-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_tbl_playerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_matchschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(max_length=50)),
                ('match_todate', models.CharField(max_length=50)),
                ('match_fromdate', models.CharField(max_length=50)),
                ('match_venue', models.CharField(max_length=50)),
            ],
        ),
    ]
