# Generated by Django 5.0.2 on 2024-03-26 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrator', '0061_tbl_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_addsrawmaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=50)),
                ('rawmaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_rawmaterial')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_unit')),
            ],
        ),
    ]
