# Generated by Django 5.0.2 on 2024-03-27 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0061_tbl_production'),
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_supplierraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Supplier_rate', models.CharField(max_length=50)),
                ('rawmaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_rawmaterial')),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_supplier')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_unit')),
            ],
        ),
    ]
