# Generated by Django 5.0.2 on 2024-03-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0002_tbl_supplierraw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_supplierraw',
            old_name='supplier_name',
            new_name='supplier',
        ),
    ]
