# Generated by Django 5.0.2 on 2024-03-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0003_rename_supplier_name_tbl_supplierraw_supplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_supplierraw',
        ),
    ]
