# Generated by Django 5.0.2 on 2024-03-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0005_tbl_supplierraw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_supplierraw',
            old_name='Supplier_rate',
            new_name='supraw_rate',
        ),
    ]
