# Generated by Django 5.0.2 on 2024-04-01 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0006_rename_supplier_rate_tbl_supplierraw_supraw_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_addsrawmaterial',
        ),
    ]
