# Generated by Django 5.0.2 on 2024-04-03 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0007_delete_tbl_addsrawmaterial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_supplierraw',
        ),
    ]
