# Generated by Django 5.0.2 on 2024-04-09 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0010_tbl_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_sales',
            name='supplier_name',
        ),
    ]
