# Generated by Django 5.0.2 on 2024-02-21 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrator', '0011_tbl_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newuser_name', models.CharField(max_length=150)),
                ('newuser_gender', models.CharField(max_length=150)),
                ('newuser_contact', models.CharField(max_length=100)),
                ('newuser_email', models.CharField(max_length=100)),
                ('newuser_password', models.CharField(max_length=100)),
                ('newuser_address', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_district')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
    ]
