# Generated by Django 5.0.2 on 2024-03-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_email', models.CharField(max_length=150)),
                ('login_password', models.CharField(max_length=50)),
            ],
        ),
    ]
