# Generated by Django 5.0.2 on 2024-04-24 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_remove_tbl_productbooking_customer_delete_tbl_pcart_and_more'),
        ('Guest', '0009_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_customer',
        ),
    ]
