# Generated by Django 5.0.2 on 2024-04-24 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0064_delete_aboutussimple'),
        ('Guest', '0010_delete_tbl_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_gender', models.CharField(max_length=150)),
                ('customer_email', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_password', models.CharField(max_length=100)),
                ('customer_photo', models.FileField(upload_to='Assets/UserPhoto/')),
                ('customer_proof', models.FileField(upload_to='Assets/UserProof/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
    ]
