# Generated by Django 5.0.2 on 2024-04-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_tbl_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_feedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
    ]
